# Generated by Django 4.2.6 on 2023-11-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountLogin', models.CharField(max_length=15, verbose_name='Имя')),
                ('AccountEmail', models.EmailField(max_length=30, verbose_name='Почта')),
                ('AccountPassword', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
        ),
    ]
